# Generated by Django 6.0.1 on 2026-02-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_persona_horassemanales'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoriaanual',
            name='titulo',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
