# Generated by Django 6.0.1 on 2026-02-16 18:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_memoriaanual_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrantememoria',
            name='horasSemanales',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Las horas semanales no pueden ser negativas')]),
        ),
    ]
